# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2018.12.10
# Revision...: --
# Purpose....: Simple compose file to create a 19.2 database
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: GPL-3.0+
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:
  tdb192s:
    image: oracle/database:19.2.0.0
    container_name: tdb192s
    hostname: tdb192s
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb192s:/u01
      - ./config:/u01/config
    ports:
      - "2192:1521"
    environment:
#      ORADBA_TEMPLATE_PREFIX: custom_
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB192S

  tdb192c:
    image: oracle/database:19.2.0.0
    container_name: tdb192c
    hostname: tdb192c
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb192c:/u01
      - ./config:/u01/config
    ports:
      - "3192:1521"
    environment:
#      ORADBA_TEMPLATE_PREFIX: custom_
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB192C
# - EOF -----------------------------------------------------------------