# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.01.17
# Revision...: --
# Purpose....: Simple compose file to create a 18.5 database
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: GPL-3.0+
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:
  tdb185s:
    image: ${DOCKER_USER}/${DOCKER_REPO}:${DOCKER_DB_VERSION}
    container_name: tdb185s
    hostname: tdb185s
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb185s:/u01
      - ./config:/u01/config
    ports:
      - "1521"
    environment:
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB185S

  tdb185c:
    image: ${DOCKER_USER}/${DOCKER_REPO}:${DOCKER_DB_VERSION}
    container_name: tdb185c
    hostname: tdb185c
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb185c:/u01
      - ./config:/u01/config
    ports:
      - "1521"
    environment:
      ORADBA_TEMPLATE_PREFIX: custom_
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB185C
# - EOF -----------------------------------------------------------------